import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google'; // 구글 폰트 가져오기
import './globals.css'; // 전역 스타일

// Geist Sans 폰트 로드 및 CSS 변수 등록
const geistSans = Geist({
  variable: '--font-geist-sans', // CSS 변수명
  subsets: ['latin'], // 서브셋 지정
});

// Geist Mono 폰트 로드 및 CSS 변수 등록
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// HTML 메타데이터 설정
export const metadata: Metadata = {
  title: 'Create Next App', // 문서 제목
  description: 'Generated by create next app', // 설명
};

/**
 * 루트 레이아웃 컴포넌트
 * 모든 페이지에서 공통으로 적용되는 구조와 스타일 포함
 */
export default function RootLayout({
  children, // 페이지 컴포넌트들이 들어오는 영역
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* 
        suppressHydrationWarning:
        서버 렌더링과 클라이언트 렌더링 불일치 시 경고 숨김
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* CSS 변수로 지정한 폰트 적용 + 스무딩 */}
        {children} {/* 실제 페이지 내용 렌더링 */}
      </body>
    </html>
  );
}
